### ISSUE TITLE
Stackable version for single extruders?

### ISSUE THREAD

**Issue by gregsvo** [Cederb/Faceshield.nu#13]
Can you make a stacked version (like the makerbot dual-extruder) but for single extruders? With minimal supports between that can be snapped/cut apart? I'm providing units for a local hospital, but am only working with single-extruder units.

I would be happy to do this myself, if you'll provide an editable file type, preferably fusion360's `. f3d` 

Thank you.

**Comment by napter** [comment]
I'm trying the istack version [here](https://www.thingiverse.com/thing:4253743/files). They all separated but one on my first try but I printed hot so I'm trying again cooler.

Here are others I've found. If you get any to work and separate nicely let me know as well please! Ideally with layer height around 0.3 for faster printing. 

- https://www.prusaprinters.org/prints/27274-3dveristan-face-shield-midsouth-makers-focus-versi/files
- https://www.thingiverse.com/thing:4255764
- https://www.thingiverse.com/thing:4247264/files

**Comment by gcormier** [comment]
Did not have any luck with the efficient stack ( https://www.thingiverse.com/thing:4253743/files ) version. Separating them ended up causing a bit of damage. (0.25mm layers, PLA+)

**Comment by gomako** [comment]
I have made a version that works ok on my printer [here](https://github.com/gomako/covid-19-face-shield). I am adding to the repo as I go. There are only stacks of two and four at the moment for testing, but I will add stacks of more over the coming days. Please let me know if they work for you by raising issues on my repo.

**Comment by Cederb** [comment]
Since stacks has to be optimized for the layer height you intend to print them in, and it therefore is impossible for me to generate one stack that fits all needs, i recommend that you all use the free version of the amazing 3D printing software LuBan and it's new stack generation feature to easily generate your single extrusion stacks. Read more here:

https://www.facebook.com/groups/1067858546711484/permalink/1491622321001769/
