### ISSUE TITLE
1 inch spacer

### ISSUE THREAD

**Issue by lgebhardt** [Cederb/Faceshield.nu#6]
I have a pack of report cover sheet material that's a bit over 11 inches. If you make the spacer 1" (25.4mm) long you don't need to turn the sheet over, just punch with and without the spacer in place. It will work with any size sheet as long as it's long enough to contain the holes. That should make it more flexible. If you only resize the one dimension the spacer will work either way.

**Comment by Cederb** [comment]
Yes, you can absolutely do this. Having a spacer fixed and just flip the sheet is the faster way of doing it when doing many in repeated fashion, since you don't have to change anything to the hole punch setting.

Btw, with true 11" sheets, you can also just set the hole punch to 12" and flip the sheet, it gives the same effect as the spacer.
